AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Generic Serverless Template for Node.js Lambda Function

Globals:
  Function:
    Timeout: 300
    MemorySize: 512

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-Function'
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: ../
      Description: A generic Lambda function example.
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /example
            Method: get
      Environment:
        Variables:
          AWS_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: "YourAccessKeyId"
          AWS_SECRET_ACCESS_KEY: "YourSecretAccessKey"
          AWS_SESSION_TOKEN: "YourSessionToken"
          # Example environment variables
          DYNAMODB_TABLE_NAME: "SampleTable"
          STRING_ENV_SAMPLE: "YourStringValue"
          NUMBER_ENV_SAMPLE: "1"
